## Input Data Schema
# feature id: feature name
# The order must be consistent with the raw data.
# First field is the label. Case insensitive here.

1: 'item_id'
2: 'item_brand_id'
3: 'item_city_id'
4: 'item_price_level'
5: 'item_sales_level'
6: 'item_collected_level'
7: 'item_pv_level'
8: 'user_id'
9: 'user_gender_id'
10: 'user_age_level'
11: 'user_occupation_id'
12: 'user_star_level'
13: 'context_id'
14: 'context_page_id'
15: 'shop_id'
16: 'shop_review_num_level'
17: 'shop_review_positive_rate'
18: 'shop_star_level'
19: 'shop_score_service'
20: 'shop_score_delivery'
21: 'shop_score_description'
22: 'is_trade'
23: 'category_0'
24: 'category_1'
25: 'category_2'
26: 'property_0'
27: 'property_1'
28: 'property_2'
29: 'week'
30: 'hour'
31: 'predict_category_0'
32: 'predict_category_1'
33: 'predict_category_2'
34: 'user_count'
35: 'item_count'


